/*  
 *   File: LonCpTypes.h
 *   Generated by LonTalk Interface Developer 4.00.11
 *
 *   Created on Thu Oct 22 11:50:57 2009
 *   This file applies to the device with program ID 9F:FF:FF:06:00:0A:04:01
 *
 *   Copyright (c) Echelon Corporation 2002-2009
 *   All rights reserved.
 *
 *   This file is Example Software as defined in the Software
 *   License Agreement that governs its use.
 *
 *   ECHELON MAKES NO REPRESENTATION, WARRANTY, OR CONDITION OF
 *   ANY KIND, EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE OR IN
 *   ANY COMMUNICATION WITH YOU, INCLUDING, BUT NOT LIMITED TO,
 *   ANY IMPLIED WARRANTIES OF MERCHANTABILITY, SATISFACTORY
 *   QUALITY, FITNESS FOR ANY PARTICULAR PURPOSE, 
 *   NONINFRINGEMENT, AND THEIR EQUIVALENTS.
 */
#if !defined(DEFINED_LONCPTYPES_H)
#define DEFINED_LONCPTYPES_H

/*
 *  Make sure to enforce a packing of 1, and a padding of 0,
 *  when compiling these type definitions. Please consult your
 *  compiler's manual for details on structure packing and padding.
 */

#endif  /* defined(DEFINED_LONCPTYPES_H) */
/* end of file. */
