/*  
 *   File: ShortStackDev.c
 *   Generated by LonTalk Interface Developer 4.00.11
 *
 *   Created on Thu Oct 22 11:50:57 2009
 *   This file applies to the device with program ID 9F:FF:FF:06:00:0A:04:01
 *
 *   Copyright (c) Echelon Corporation 2002-2009
 *   All rights reserved.
 *
 *   This file is Example Software as defined in the Software
 *   License Agreement that governs its use.
 *
 *   ECHELON MAKES NO REPRESENTATION, WARRANTY, OR CONDITION OF
 *   ANY KIND, EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE OR IN
 *   ANY COMMUNICATION WITH YOU, INCLUDING, BUT NOT LIMITED TO,
 *   ANY IMPLIED WARRANTIES OF MERCHANTABILITY, SATISFACTORY
 *   QUALITY, FITNESS FOR ANY PARTICULAR PURPOSE, 
 *   NONINFRINGEMENT, AND THEIR EQUIVALENTS.
 */
#if !defined(DEFINED_SHORTSTACKDEV_C)
#define DEFINED_SHORTSTACKDEV_C

#include <string.h>
#include "ShortStackDev.h"
#include "ShortStackApi.h"

/*
 *  Network Variables
 *  The device's network variables are being declared here.
 *  Input network variables are automatically updated by the
 *  ShortStack API, with the help of the network variable definitions
 *  table and the LonEventHandler function. The application receives
 *  notification through the LonNvUpdateOccurred callback. 
 *  Output network variables must be written to by the application,
 *  just like any other global variable may be written to. For
 *  output network variables, the application must also call the 
 *  LonPropagateNv() API function to submit the updated output
 *  network variable data to the ShortStack Micro Server.
 */
volatile SNVT_volt nviVolt = { 0, 0x34 } ;   /* sd_string("@0|1") */

SNVT_volt nvoVoltFb;          /* sd_string("@0|2") */



/*
 *  Self-identification data
 *  DO NOT EDIT
 */
static const LonByte siData[] =
{
    0x00, 0x3D, 0x02, 0x00, 0x00, 0x8E, 0x2C, 0x8E, 
    0x2C, 0x26, 0x33, 0x2E, 0x34, 0x40, 0x34, 0x56, 
    0x6F, 0x6C, 0x74, 0x41, 0x63, 0x74, 0x75, 0x61, 
    0x74, 0x6F, 0x72, 0x00, 0x30, 0x6E, 0x76, 0x69, 
    0x56, 0x6F, 0x6C, 0x74, 0x00, 0x40, 0x30, 0x7C, 
    0x31, 0x00, 0x30, 0x6E, 0x76, 0x6F, 0x56, 0x6F, 
    0x6C, 0x74, 0x46, 0x62, 0x00, 0x40, 0x30, 0x7C, 
    0x32, 0x00, 0x7F, 0x00, 0x7F
};

/*
 *  Application initialization data
 *  DO NOT EDIT - Ha!
 */
static const LonByte appInitData[] =
{
    /* 16-bit application signature: */
    LON_APP_SIGNATURE/256u, LON_APP_SIGNATURE%256u,

    /* program Id: */
	// ed2dani - just changing this to confim what is loaded in Neuron
    0x9F, 0xFF, 0xFF, 0x06, 0x00, 0x0A, 0x04, 0x02,

    /* communication parameters: */
	// ed2dani - according to page 35, table 6 - all zeros mean 'remain at default'
    0x25, 0x2E, 0x08, 0x05, 0x0C, 0x0E, 0x0F, 0x00,
    0x04, 0x00, 0xA4, 0x00, 0x00, 0x00, 0x00, 0x00,
	// 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
	// 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,

    /* preferences */
    LON_EXPLICIT_ADDRESSING | LON_SERVICE_PIN_TIMER,
    /* number of static network variables: */
    0x02, 
    /* one configuration byte per network variable: */
    0x00, 0x60
};

/*
 *  Network Variable Table
 *  The network variable table nvTable[] is defined here, where each element
 *  of that array has the structure detailed in the following definition.
 */

#define NVPTR  volatile void* const    /* helper for following table */

static const LonNvDescription nvTable[] =
{ /*          name       declared size                 flags */
   { (NVPTR)&nviVolt,   (LonByte)sizeof(SNVT_volt),    0 },
   { (NVPTR)&nvoVoltFb, (LonByte)sizeof(SNVT_volt),    LON_NVDESC_OUTPUT_MASK }
}; /* end of Nv table */
const LonByte* LonGetSiData(unsigned* pLength)
{
    *pLength = (unsigned)sizeof(siData);
    return siData;
}

const LonByte* LonGetAppInitData(void)
{
    return appInitData;
}

const LonNvDescription* const LonGetNvTable(void)
{
    return nvTable;
}

const LonMtDescription* const LonGetMtTable(void)
{
    return NULL;
}

#endif  /* defined(DEFINED_SHORTSTACKDEV_C) */
/* end of file. */
